### ISSUE TITLE
useful_booksの更新

### ISSUE THREAD

**Issue by ktngch** [op19-it-edu/base-docs#31]
糸井さんからご要望があったので、Docker（コンテナ仮想化技術）に関する本を追記したいなと思ってます。他に関心のある分野があれば、（読んでる本の範囲で）対応するので、ご提案どうぞ〜

**Comment by 3-yuma-3** [comment]
今のところ、Docker以外特に要望はないです。。  
宜しくお願いします。

**Comment by ktngch** [comment]
https://github.com/op19-it-edu/base-docs/wiki/useful_books
こちらで対応済みです

**Comment by xinxin-pipa** [comment]
さっきほど糸井さんが書いたAPIドキュメントを読んだが、内容がなんとなくわかるけど、書き方全くわからないです。何かおすすめのツールや本とかあるでしょうか。
まだ全然自分で調べてなくて、直接に聞きに来るのがあんまりよくないかなと思いつつ、うん。。。

**Comment by ktngch** [comment]
> 何かおすすめのツールや本とかあるでしょうか。

今から福岡へフライトなので、到着後なにか提案しますw

**Comment by xinxin-pipa** [comment]
気をつけて行ってらっしゃい！笑
来週の土曜私も福岡へフライトです
